### ISSUE TITLE
Blockchain?

### ISSUE THREAD

**Issue by ryanteck** [ryanteck/pi-claw-v2#2]
Could we integrate the blockchain some how? Each play is recorded by the blockchain for authenticity?

**Comment by ThePiLocator** [comment]
You can try to create your own coin.
What's the advantage of create your own coin? I don't know, but this could be analogous of when you go to a place directly and give "2 euro in exchange of coin for a game".
Moreover, If this becomes a big thing, many people will buy it and the value of the coin could really go to the stars (imo).

**Comment by ryanteck** [comment]
no
